### ISSUE TITLE
persistent ability after login

### ISSUE THREAD

**Issue by afrijaldz** [stalniy/casl-react-example#3]
Hello,
In the ability.js I use
```
/* eslint-disable no-underscore-dangle */
import { Ability, AbilityBuilder } from '@casl/ability'

function subjectName(item) {
  if (!item || typeof item === 'string') {
    return item
  }

  return item.__type
}

export default new Ability([])
```

and I update the ability when login using ability.update(rules). The rules is come from api.
But, when I refresh the page, the ability is empty array again.
How to make the ability persistence?

**Comment by stalniy** [comment]
It depends on where you store rules (you need to store them somewhere in order to update on refresh).

If you use redux or mobx, then save it somewhere in redux state and persist redux/mobx store
